services:
  open3a:
    image: patricklammers1991/open3a:latest
    ports:
      - "8080:80"
    restart: always
    volumes:
      - /dbdata:/var/www/html/system/DBData
      - /backup:/var/www/html/system/Backup
      - /specifics:/var/www/html/specifics

